# Stackleberg 
# Market Demand Curve

P = a  -  b * Q

# Where Q is the market quantity demanded and P is the market price in dollars
# The firms create the quantity 
# Lets assume two firms qa and qb

Q = qa + qb 

# Marginal cost is the cost it takes to create a single unit of quantity
# each firm can incurr different costs and have varying marginal costs
# We can assume a constant marginal cost for both firms ; MCa ,  MCb
# Market demand curve

P = a  -  b * (qa + qb)

# Calculate The Leaders First Step
# ====================================
# Begin backward induction to determine
# what the reaction would be of firm b. 
# Since firm a will move first , it will 
# need to anticipate what firm b will do.
#
# 1. Calculate Firm B's reaction
# 2. Calculate Firm A's response 
# 3. Implment Firm A's response
# 4. Calculate Firm B's response given A's response
# 
# Firm B Reaction Function:
# -------------------------
# Total Revenue is price multiplied by quantity

TRb = P * qb 

# Substitute solution for P and multiply by qb
TRb = (a -( b * (qa + qb) )) * qb

# Treat qA as a constant because firm B can’t change the quantity of output produced by firm A.
# marginal revenue is the derivative of what total revenue by b over quantity provided by b  rate
MRb = d_TRb/d_qb = a-b*qa-qb

# Maximize profit by setting marginal revenue to marginal cost
MRb = MCb =  a-b*qa-qb

# Solve for qb to get the reaction function
qb = a-MCb-b*qa

# Firm A Response Function :
# -------------------------
# Market demand curve
P = a  -  b * (qa + (qb))

# Substitue B reaction into A's demand curve
P = a - b*(qa + (a-b*qa-MCb))
P = a - b*qa - b*(a-b*qa-MCb)
P = a - b*qa - b*a + b*b*qa + b*MCb

# Total Revenue is price multiplied by quantity
TRa = P * qa = (a - b*qa - b*a + b*b*qa + b*MCb) * qa
TRa = qa*a - qa*b*qa - qa*b*a + qa*b*b*qa + qa*b*MCb 
TRa = qa*a - qa*qa*b - qa*b*a + qa*qa*b*b + qa*b*MCb 
  
# Calculate the marginal revenue by taking the derivative of the Total Revenue of A, with resepect to the quantity generated by A
MRa = d_TRa/d_qa = a - 2*qa*b - b*a + 2*qa*b*b + b*MCb

# Firm A deterines the profit mazimizing quantity to output by setting the marginal revenue equal to marginal cost and solving for qa

MRa = MCa 
# solve for qa
MCa = a - 2*qa*b - b*a + 2*qa*b*b + b*MCb

0 = a - 2*qa*b - b*a + 2*qa*b*b + b*MCb - MCa
2*qa*b - 2*qa*b*b = a - b*a + b*MCb - MCa
2*b(qa - qa*b) = a - b*a + b*MCb - MCa
(qa - qa*b) = (a - b*a + b*MCb - MCa) * (1/2*b)
qa*(1-b) = (a - b*a + b*MCb - MCa) * (1/2*b)
qa = (a - b*a + b*MCb - MCa) * (1/2*b) * (1/(1-b))

(120 - 0.5*120 + 0.5*34 - 20) * (1/2*0.5) * (1/(1-0.5))

# The response of qa can now be determined from knowing hte demand curve, and the marginal cost of firm B

# Knowing that firm a will implement the most profitable response lets pretend that it has been iplemented, and now we can resolve and discover what firm B's actual reaction turns out to be if it seeks to maximize at this point.

# Solve for qb to get the reaction function
qb = a-MCb-b*qa
# substitute qa move to detect what qb's move

qb = a - MCb - b* 
